export const stats = [
  { value: "50K+", label: "Active minds" },
  { value: "1M+", label: "Hours learned" },
  { value: "97%", label: "Retention" },
  { value: "95+", label: "Languages" },
] as const;

export const pathways = [
  {
    id: "health",
    kicker: "01  Health",
    title: "Longevity science",
    modules: "40+ modules",
    image: "/images/health.jpg",
    copy: "Master biohacking, optimize your biology, and extend healthspan with protocols that respect circadian rhythm, recovery, and the long game.",
  },
  {
    id: "wealth",
    kicker: "02  Wealth",
    title: "Financial mastery",
    modules: "35+ modules",
    image: "/images/wealth.jpg",
    copy: "Build generational wealth through investing systems, business architecture, and financial intelligence that compounds quietly.",
  },
  {
    id: "intelligence",
    kicker: "03  Intelligence",
    title: "Cognitive enhancement",
    modules: "50+ modules",
    image: "/images/intelligence.jpg",
    copy: "Upgrade working memory, attention, and reasoning with neuroscience-backed technique and an AI mentor that learns how you learn.",
  },
  {
    id: "mastery",
    kicker: "04  Mastery",
    title: "Real-world execution",
    modules: "40+ modules",
    image: "/images/mastery.jpg",
    copy: "Turn knowledge into skill. Teach what you know, monetize what you master, and let practice rewrite the nervous system.",
  },
  {
    id: "ai",
    kicker: "05  AI",
    title: "Artificial intelligence",
    modules: "Flagship track",
    image: "/images/ai.jpg",
    copy: "Master modern AI — from prompt engineering and LLMs to building agents, fine-tuning models, and shipping AI products.",
  },
  {
    id: "creation",
    kicker: "06  Creation",
    title: "Innovation lab",
    modules: "Unlimited potential",
    image: "/images/creation.jpg",
    copy: "Transform ideas into reality with creative amplification tools and innovation frameworks.",
  },
] as const;

export const milestones = [
  {
    year: 2024,
    title: "AI revolution",
    copy: "Frontier models crossed from novelty into daily cognition. The first generation of people who think with a second mind.",
  },
  {
    year: 2026,
    title: "Cognitive augmentation",
    copy: "Mentorship, memory, and measurement fuse. Learning stops being content and becomes a living protocol.",
  },
  {
    year: 2028,
    title: "Personalized longevity",
    copy: "Healthspan protocols leave the clinic. Sleep, fuel, and recovery are tuned to the same loop as intelligence.",
  },
  {
    year: 2032,
    title: "Neural interfaces",
    copy: "Bandwidth between mind and machine rises. Attention becomes a scarce, trained instrument.",
  },
  {
    year: 2038,
    title: "Collective intelligence",
    copy: "Networks of augmented minds outpace any single genius. Mastery is no longer hoarded; it is composed.",
  },
  {
    year: 2045,
    title: "Universal prosperity",
    copy: "Work becomes optional for those who trained the mind that builds. The scarce resource is no longer labor — it is direction.",
  },
] as const;

export const principles = [
  {
    title: "Neuroscience-based learning",
    copy: "Dopamine-aware sequencing, spaced retrieval, and neuroplasticity windows — not binge content.",
  },
  {
    title: "A mentor that adapts",
    copy: "Lucien learns your cognitive patterns and rebuilds the path as you change. Retention, not throughput.",
  },
  {
    title: "Peak performance",
    copy: "Mental and physical protocols in one loop: sleep, focus, fuel, and the work that actually ships.",
  },
] as const;

export const science = [
  {
    title: "Retrieval practice",
    source: "Roediger & Karpicke, 2006",
    copy: "Lessons are structured around active recall — the most replicated finding in the science of learning.",
  },
  {
    title: "Spaced repetition",
    source: "Ebbinghaus, 1885 · Cepeda et al., 2008",
    copy: "Pacing and review intervals are tuned to your forgetting curve, not arbitrary calendars.",
  },
  {
    title: "Metacognitive calibration",
    source: "Dunlosky & Metcalfe, 2008",
    copy: "Lucien checks what you actually know vs. what you think you know — and adjusts.",
  },
] as const;

export const generateSteps = [
  {
    n: "01",
    title: "Type any topic",
    copy: "From “quantum computing” to “negotiation tactics”. Lucien understands what you mean.",
  },
  {
    n: "02",
    title: "AI builds your course",
    copy: "Modules, lessons, examples, quizzes — generated for your level in under a minute.",
  },
  {
    n: "03",
    title: "Start learning",
    copy: "Lucien teaches it, answers your questions, and adapts as you go.",
  },
] as const;

export const courseTraits = [
  {
    title: "Any topic, any depth",
    copy: "From “linear algebra” to “selling SaaS to enterprise”. If you can name it, Lucien can teach it.",
  },
  {
    title: "Built in under a minute",
    copy: "No course catalogs. No “coming soon”. The course you need is ready before your coffee cools.",
  },
  {
    title: "Calibrated to your level",
    copy: "Beginner today, advanced tomorrow. Each lesson is shaped by what you already know.",
  },
  {
    title: "Outcome-driven lessons",
    copy: "Every module ends with a check: did you actually learn it? If not, the course adjusts.",
  },
  {
    title: "Adapts as you learn",
    copy: "Pacing, examples, and difficulty curve quietly retune themselves the more you use it.",
  },
  {
    title: "Earn real proof",
    copy: "Pass the final assessment and walk away with a verifiable certificate — not just a vibe.",
  },
] as const;

export const journey = [
  {
    id: "discover",
    step: "01",
    kicker: "Discover",
    title: "Discover your DNA",
    copy: "Lucien maps your cognitive strengths, learning style, and knowledge gaps.",
    points: [
      "AI-powered cognitive assessment",
      "Learning style fingerprint",
      "Personalized roadmap generated",
    ],
  },
  {
    id: "orient",
    step: "02",
    kicker: "Orient",
    title: "Calibrate your level",
    copy: "Beginner today, advanced tomorrow. Each lesson is shaped by what you already know.",
    points: ["Prior knowledge probe", "Difficulty set honestly", "No assumed catalog"],
  },
  {
    id: "generate",
    step: "03",
    kicker: "Generate",
    title: "AI builds your course",
    copy: "Modules, lessons, examples, quizzes — generated for your level in under a minute.",
    points: ["Any topic, any depth", "Evidence-cited lessons", "Built to change how you think"],
  },
  {
    id: "learn",
    step: "04",
    kicker: "Learn",
    title: "First lesson in 60 seconds",
    copy: "You start before the coffee cools. Lucien teaches it and answers as you go.",
    points: ["Natural conversation", "95+ languages", "Real-time synthesis"],
  },
  {
    id: "retrieve",
    step: "05",
    kicker: "Retrieve",
    title: "Spaced recall loops",
    copy: "Dopamine-aware sequencing, spaced retrieval, and neuroplasticity windows — not binge content.",
    points: ["Active recall", "Forgetting-curve pacing", "No arbitrary calendar"],
  },
  {
    id: "adapt",
    step: "06",
    kicker: "Adapt",
    title: "Lucien retunes the path",
    copy: "Pacing, examples, and difficulty curve quietly retune themselves the more you use it.",
    points: ["Living cognitive model", "Blind spots named", "Flow protected"],
  },
  {
    id: "prove",
    step: "07",
    kicker: "Prove",
    title: "Earn real proof",
    copy: "Every module ends with a check: did you actually learn it? If not, the course adjusts.",
    points: ["Outcome-driven lessons", "Final assessment", "Verifiable certificate"],
  },
  {
    id: "master",
    step: "08",
    kicker: "Master",
    title: "From curious to mastery",
    copy: "Turn knowledge into skill. Teach what you know, monetize what you master, and let practice rewrite the nervous system.",
    points: ["Embodied practice", "Teach to keep", "Compound the skill"],
  },
] as const;

export const agents = [
  {
    id: "lucien",
    name: "Lucien",
    role: "Adaptive Super Mentor",
    epithet: "The Polymath Oracle",
    domain: "Flagship",
    copy: "Your unfair advantage, on demand.",
    featured: true,
  },
  {
    id: "atlas",
    name: "Atlas",
    role: "Startup Architect",
    epithet: "The Strategic General",
    domain: "Business",
    copy: "From zero to funded. Every move calculated.",
    featured: true,
  },
  {
    id: "helix",
    name: "Helix",
    role: "Biohacker Prime",
    epithet: "The Bio-Engineer",
    domain: "Health",
    copy: "Optimize the machine that runs everything else.",
    featured: true,
  },
  {
    id: "forge",
    name: "Forge",
    role: "Engineering Mind",
    epithet: "The Systems Philosopher",
    domain: "Tech",
    copy: "Build systems that scale to infinity.",
    featured: true,
  },
  {
    id: "meridian",
    name: "Meridian",
    role: "Wealth Strategist",
    epithet: "The Patient Architect",
    domain: "Finance",
    copy: "Think in decades. Compound everything.",
    featured: true,
  },
  {
    id: "muse",
    name: "Muse",
    role: "Creative Catalyst",
    epithet: "The Creative Alchemist",
    domain: "Creative",
    copy: "See what others can’t. Build what they won’t.",
    featured: true,
  },
  {
    id: "synapse",
    name: "Synapse",
    role: "Neuro Architect",
    epithet: "The Mind Sculptor",
    domain: "Mind",
    copy: "Unlock another layer of your mind.",
    featured: true,
  },
  {
    id: "quanta",
    name: "Quanta",
    role: "Quantum Intelligence",
    epithet: "The Probability Weaver",
    domain: "Future",
    copy: "Think in superpositions. Solve the unsolvable.",
    featured: true,
  },
  {
    id: "nova",
    name: "Nova",
    role: "Space & Frontier Tech",
    epithet: "The Orbital Strategist",
    domain: "Future",
    copy: "Build for the next frontier. Earth is just the beginning.",
    featured: true,
  },
  {
    id: "genome",
    name: "Genome",
    role: "Biotech Architect",
    epithet: "The Bio-Programmer",
    domain: "Future",
    copy: "Rewrite the code of life itself.",
    featured: true,
  },
  {
    id: "terra",
    name: "Terra",
    role: "Climate & Sustainability",
    epithet: "The Regenerative Strategist",
    domain: "Future",
    copy: "Build the future the planet needs.",
    featured: true,
  },
  {
    id: "axiom",
    name: "Axiom",
    role: "Robotics & Automation",
    epithet: "The Precision Engineer",
    domain: "Future",
    copy: "Automate everything. Amplify the human.",
    featured: true,
  },
  {
    id: "lyra",
    name: "Lyra",
    role: "Language Architect",
    epithet: "The Polyglot",
    domain: "Mind",
    copy: "Ninety-five languages. One cognitive model.",
    featured: false,
  },
  {
    id: "prism",
    name: "Prism",
    role: "Perception Designer",
    epithet: "The Seeing Mind",
    domain: "Creative",
    copy: "Train the eye that notices what others skip.",
    featured: false,
  },
  {
    id: "solace",
    name: "Solace",
    role: "Recovery Protocol",
    epithet: "The Rest Engineer",
    domain: "Health",
    copy: "Sleep, fuel, and the quiet that makes intelligence possible.",
    featured: false,
  },
  {
    id: "cipher",
    name: "Cipher",
    role: "Security Mind",
    epithet: "The Quiet Guardian",
    domain: "Tech",
    copy: "Threat models first. Then the system that cannot be rushed.",
    featured: false,
  },
  {
    id: "vesper",
    name: "Vesper",
    role: "Philosophy Guide",
    epithet: "The Still Question",
    domain: "Mind",
    copy: "Direction is the scarce resource. Think before you optimize.",
    featured: false,
  },
  {
    id: "pulse",
    name: "Pulse",
    role: "Athletic Intelligence",
    epithet: "The Body Tutor",
    domain: "Health",
    copy: "The nervous system learns in motion. Practice is the curriculum.",
    featured: false,
  },
  {
    id: "loom",
    name: "Loom",
    role: "Narrative Craft",
    epithet: "The Storywright",
    domain: "Creative",
    copy: "Write so the idea survives contact with another mind.",
    featured: false,
  },
  {
    id: "nadir",
    name: "Nadir",
    role: "Risk Architect",
    epithet: "The Downside Cartographer",
    domain: "Finance",
    copy: "Compound only what you can keep. Map the loss before the gain.",
    featured: false,
  },
  {
    id: "ember",
    name: "Ember",
    role: "Energy Systems",
    epithet: "The Grid Mind",
    domain: "Future",
    copy: "Power, heat, and the physics that every other ambition sits on.",
    featured: false,
  },
  {
    id: "halo",
    name: "Halo",
    role: "Ethics Counsel",
    epithet: "The Limit Keeper",
    domain: "Mind",
    copy: "Clear limits on what an agent will and will not do.",
    featured: false,
  },
  {
    id: "origin",
    name: "Origin",
    role: "Foundations Mentor",
    epithet: "The First Principles",
    domain: "Tech",
    copy: "Start at the atom. Build only what must exist.",
    featured: false,
  },
  {
    id: "kepler",
    name: "Kepler",
    role: "Systems of Nature",
    epithet: "The Pattern Reader",
    domain: "Future",
    copy: "Astronomy, ecology, and the long clock the planet already runs.",
    featured: false,
  },
] as const;

export const campusStops = [
  { id: "core", label: "Lucien core", copy: "The digital neural mentor. Not a person — a field." },
  { id: "health", label: "Health", copy: "Longevity science. The machine that runs everything else." },
  { id: "wealth", label: "Wealth", copy: "Financial mastery. Think in decades." },
  { id: "intelligence", label: "Intelligence", copy: "Cognitive enhancement. Upgrade the instrument." },
  { id: "mastery", label: "Mastery", copy: "Real-world execution. Practice rewrites the nervous system." },
  { id: "ai", label: "AI", copy: "Build agents. Ship the product. Keep the human in command." },
  { id: "creation", label: "Creation", copy: "Innovation lab. Turn the idea into a thing that exists." },
] as const;

export const series = {
  lucien: { name: "Lucien", fill: "var(--color-series-lucien)" },
  generic: { name: "Generic tutor", fill: "var(--color-series-generic)" },
  lecture: { name: "Lecture course", fill: "var(--color-series-trad)" },
} as const;

export const evidence = [
  {
    id: "retention",
    label: "Retention",
    title: "Spaced retrieval, 12 weeks",
    kind: "line" as const,
    xKey: "w",
    xLabel: "Weeks",
    yLabel: "Retention",
    ySuffix: "%",
    yDomain: [0, 100] as [number, number],
    copy: "Dopamine-aware sequencing, spaced retrieval, and neuroplasticity windows — not binge content.",
    data: [
      { w: 0, lucien: 42, generic: 42, lecture: 42 },
      { w: 2, lucien: 61, generic: 50, lecture: 46 },
      { w: 4, lucien: 74, generic: 54, lecture: 38 },
      { w: 6, lucien: 84, generic: 55, lecture: 32 },
      { w: 8, lucien: 91, generic: 54, lecture: 29 },
      { w: 10, lucien: 95, generic: 53, lecture: 26 },
      { w: 12, lucien: 97, generic: 52, lecture: 24 },
    ],
  },
  {
    id: "score",
    label: "Twelve weeks",
    title: "Retention at 12 weeks",
    kind: "bar" as const,
    ySuffix: "%",
    copy: "Retention, not throughput.",
    data: [
      { name: "Lucien", value: 97, key: "lucien" as const },
      { name: "Generic tutor", value: 52, key: "generic" as const },
      { name: "Lecture course", value: 24, key: "lecture" as const },
    ],
  },
  {
    id: "mastery",
    label: "Time to skill",
    title: "Hours to practiced skill",
    kind: "line" as const,
    xKey: "h",
    xLabel: "Hours",
    yLabel: "Mastery",
    ySuffix: "%",
    yDomain: [0, 100] as [number, number],
    copy: "Turn knowledge into skill. Teach what you know, monetize what you master, and let practice rewrite the nervous system.",
    data: [
      { h: 0, lucien: 0, generic: 0, lecture: 0 },
      { h: 10, lucien: 38, generic: 14, lecture: 10 },
      { h: 20, lucien: 58, generic: 24, lecture: 18 },
      { h: 40, lucien: 76, generic: 38, lecture: 30 },
      { h: 80, lucien: 90, generic: 52, lecture: 44 },
      { h: 120, lucien: 97, generic: 61, lecture: 54 },
    ],
  },
  {
    id: "focus",
    label: "Focus",
    title: "Deep work, minutes",
    kind: "line" as const,
    xKey: "w",
    xLabel: "Weeks",
    yLabel: "Minutes",
    ySuffix: "m",
    yDomain: [0, 120] as [number, number],
    copy: "Mental and physical protocols in one loop: sleep, focus, fuel, and the work that actually ships.",
    data: [
      { w: 0, lucien: 25, generic: 25, lecture: 25 },
      { w: 2, lucien: 40, generic: 28, lecture: 26 },
      { w: 4, lucien: 58, generic: 32, lecture: 28 },
      { w: 6, lucien: 74, generic: 35, lecture: 29 },
      { w: 8, lucien: 88, generic: 36, lecture: 30 },
      { w: 12, lucien: 110, generic: 38, lecture: 30 },
    ],
  },
] as const;
